var habs ={"type": "FeatureCollection","features": [
{"features": [{"geometry": {"coordinates": [-131.597062, 55.318142], "type": "Point"}, "properties": {"popupContent": "Chief Kashakes' House, Mile 2.5 South Tongass Highway, Saxman, Ketchikan Gateway Borough, AKbrHABS AK-190 ;<br> Building/structure dates: 1895 Initial Construction ;<br> National Register of Historic Places NRIS Number: 93000338<br>https://www.loc.gov/item/ak0436<br>https://www.loc.gov/item/ak0436", "town": "Saxman,  Ketchikan Gateway Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-149.361662, 61.460679], "type": "Point"}, "properties": {"popupContent": "St. Nicholas Russian Orthodox Churches, New Church, Eklutna, Anchorage Borough, AKbrHABS AK-94-B ;<br> Building/structure dates: 1962 Initial Construction<br>https://www.loc.gov/item/ak0329<br>https://www.loc.gov/item/ak0329", "town": "Eklutna,  Anchorage Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-170.280888, 57.12088], "type": "Point"}, "properties": {"popupContent": "Saints Peter & Paul Russian Orthodox Church, Church Street, Saint Paul, Aleutians West Census Area, AKbrHABS AK-51 ;<br> National Register of Historic Places NRIS Number: 80000744<br>https://www.loc.gov/item/ak0258<br>https://www.loc.gov/item/ak0258", "town": "Saint Paul,  Aleutians West Census Area,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-166.536174, 53.87549], "type": "Point"}, "properties": {"popupContent": "Holy Ascension Russian Orthodox Church, Unalaska Island, Unalaska, Aleutian Islands, AKbrHABS AK-37-A ;<br> Building/structure dates: 1894-1896 Initial Construction ;<br> Building/structure dates: ca. 1910 Subsequent Work ;<br> Building/structure dates: before 1961  ;<br> National Register of Historic Places NRIS Number: 70000112<br>https://www.loc.gov/item/ak0101<br>https://www.loc.gov/item/ak0101", "town": "Unalaska,  Aleutian Islands,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-166.548307, 53.885657], "type": "Point"}, "properties": {"popupContent": "Naval Operating Base Dutch Harbor & Fort Mears, Unalaska, Aleutian Islands, AKbrHABS AK-34 ;<br> Building/structure dates: 1947 Initial Construction ;<br> Building/structure dates: ca. 1987 Demolished ;<br> National Register of Historic Places NRIS Number: 85002733<br>https://www.loc.gov/item/ak0047<br>https://www.loc.gov/item/ak0047", "town": "Unalaska,  Aleutian Islands,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-152.403358, 57.787663], "type": "Point"}, "properties": {"popupContent": "Russian-American Company Magazin, 101 Marine Way East, Kodiak, Kodiak Island Borough, AKbrHABS AK-2 ;<br> Building/structure dates: 1793 Initial Construction ;<br> Building/structure dates: 1883 Subsequent Work ;<br> National Register of Historic Places NRIS Number: 66000954<br>https://www.loc.gov/item/ak0005<br>https://www.loc.gov/item/ak0005", "town": "Kodiak,  Kodiak Island Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-152.34329, 57.83214], "type": "Point"}, "properties": {"popupContent": "Kodiak Naval Operating Base, U.S. Coast Guard Station, Kodiak, Kodiak Island Borough, AKbrHABS AK-47 ;<br> National Register of Historic Places NRIS Number: 85002731<br>https://www.loc.gov/item/ak0454<br>https://www.loc.gov/item/ak0454", "town": "Kodiak,  Kodiak Island Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-152.500033, 57.737695], "type": "Point"}, "properties": {"popupContent": "Kodiak Naval Operating Base, Boat House, U.S. Coast Guard Station, across the taxiway from Building No. 25 on Nyman Peninsula, Kodiak, Kodiak Island Borough, AKbrHABS AK-47-I ;<br> Building/structure dates: 1942 Initial Construction ;<br> National Register of Historic Places NRIS Number: 85002731<br>https://www.loc.gov/item/ak0461<br>https://www.loc.gov/item/ak0461", "town": "Kodiak,  Kodiak Island Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-152.503721, 57.737949], "type": "Point"}, "properties": {"popupContent": "Kodiak Naval Operating Base, Aircraft Storehouse, U.S. Coast Guard Station, Albatross Avenue near Cape Spencer Street, Kodiak, Kodiak Island Borough, AKbrHABS AK-47-K ;<br> Building/structure dates: 1942 Initial Construction ;<br> National Register of Historic Places NRIS Number: 85002731<br>https://www.loc.gov/item/ak0463<br>https://www.loc.gov/item/ak0463", "town": "Kodiak,  Kodiak Island Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
{"features": [{"geometry": {"coordinates": [-152.488234, 57.750164], "type": "Point"}, "properties": {"popupContent": "U.S. Coast Guard Station, Crash Boat House, U.S. Coast Guard Station, Kodiak, Kodiak Island Borough, AKbrHABS AK-48-B ;<br> Building/structure dates: 1954 Initial Construction<br>https://www.loc.gov/item/ak0085<br>https://www.loc.gov/item/ak0085", "town": "Kodiak,  Kodiak Island Borough,  AK"}, "type": "Feature"}], "type": "FeatureCollection"},
]
}